version: '2'
services:
  ## Microservice 1
  # Image api source
  image:
    image: busybox
    volumes:
      - ./image-api:/var/www/site

  # Image api reverse proxy
  image_nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - image
    ports:
      - 8081:80
    links:
      - image_php:php

  # Image api php-fpm
  image_php:
    image: php:fpm-alpine
    volumes_from:
      - image

  # Image api logshipper
  image_filebeat:
    image: prima/filebeat:5-rc
    volumes:
      - ./filebeat.yml:/filebeat.yml
    volumes_from:
      - image
    links:
      - logstash


  ## Microservice 2
  # Content api source
  content:
    image: busybox
    volumes:
      - ./content-api:/var/www/site

  # Content api reverse proxy
  content_nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - content
    ports:
      - 8080:80
    links:
      - content_php:php

  # Content api php-fpm
  content_php:
    image: php:fpm-alpine
    volumes_from:
      - content

  # Content api log shipper
  content_filebeat:
    image: prima/filebeat:5-rc
    volumes:
      - ./filebeat.yml:/filebeat.yml
    volumes_from:
      - content
    links:
      - logstash


  ## Elastic Stack (ELK)
  logstash:
    image: logstash:5
    volumes:
      - ./logstash.conf:/logstash.conf
    command: -f /logstash.conf
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:5

  kibana:
    image: kibana:5
    ports:
      - 5601:5601
    links:
      - elasticsearch